<?php
/**
 * SABP Chatbot — Seed FAQ Knowledge Base
 * Enhanced with Hinglish keywords and LPC/salary/leave FAQs.
 * Run once after migration to populate chatbot_faqs.
 */
require __DIR__ . '/../config.php';

$faqs = [

    // ─── COMMON (all roles) ─────────────────────────────────────
    ['all','password,change password,reset password,forgot password,password badlo,password bhul gaya',
     'How do I change my password?',
     'Go to the <b>Forgot Password</b> page from the login screen and enter your registered email. You will receive a password reset link. Alternatively, contact the Admin to reset it for you.',10],

    ['all','2fa,two factor,authenticator,google authenticator,setup 2fa,otp,otp setup',
     'How do I set up Two-Factor Authentication?',
     'On your first login, you will be redirected to the <b>Setup 2FA</b> page. Scan the QR code with the Google Authenticator app on your phone. After setup, you will need to enter a 6-digit code from the app on every login.',10],

    ['all','profile,my profile,view profile,edit profile,mera profile,profile dekhna',
     'How do I view or edit my profile?',
     'Click the <b>profile icon</b> (person avatar) in the top-right corner of any page to view your profile details.',8],

    ['all','sabp,what is sabp,about sabp,portal,about portal,sabp kya hai',
     'What is SABP?',
     'SABP stands for <b>Security Attendance and Billing Portal</b>. It is used by Mahanadi Coalfields Limited (MCL) to manage security personnel attendance, generate monthly reports, handle approvals through a multi-level workflow, and process billing (LPC/LPP).',10],

    ['all','logout,log out,sign out,how to logout,logout kaise kare',
     'How do I logout?',
     'Click the <b>Logout</b> button in the sidebar menu or at the top-right corner of the page. Your session will be ended securely.',5],

    ['all','contact,support,help,helpdesk,admin contact,sampark,madad',
     'How do I contact support?',
     'For any issues, please contact the <b>System Administrator</b> or raise a request through your department head. For technical issues, email the IT helpdesk.',5],

    ['all','dark mode,theme,night mode,dark theme,light mode,dark mode kaise kare',
     'How do I switch to dark mode?',
     'Click the <b>🌙 moon icon</b> button in the top header bar. Click it again (☀️ sun icon) to switch back to light mode. Your preference is saved automatically.',6],

    ['all','locked,account locked,too many attempts,otp locked,account band',
     'My account is locked. What should I do?',
     'Your account gets locked for <b>2 hours</b> after 5 consecutive failed OTP attempts. Wait for the lockout period to expire, or contact the Admin to unlock your account.',8],

    ['all','attendance status,what is p,what is a,what is l,what is pp,status meaning,p ka matlab,a ka matlab',
     'What do attendance statuses mean?',
     '<b>P</b> = Present<br><b>A</b> = Absent<br><b>L</b> = Leave<br><b>PP</b> = Present + Overtime<br>These codes are used across all attendance reports in the portal.',8],

    ['all','approval workflow,approval process,how approvals work,approval steps,approval kaise hota,approval chain',
     'How does the approval workflow work?',
     'Monthly attendance goes through a <b>multi-level approval</b> chain:<br>1️⃣ <b>ASO</b> submits → 2️⃣ <b>APM</b> approves → 3️⃣ <b>GM</b> approves → 4️⃣ <b>HQSO</b> approves → 5️⃣ <b>SDHOD</b> finalizes and generates LPC → 6️⃣ <b>Finance</b> approves LPC for billing.',10],

    ['all','what is lpc,lpc kya hai,lpc meaning,last pay certificate,lpc full form',
     'What is LPC?',
     '<b>LPC</b> stands for <b>Last Pay Certificate</b>. It is a document generated by SDHOD after monthly attendance is approved through all levels. It contains wage calculations and billing details for security personnel. Finance department gives final approval for payment processing.',10],

    ['all','what is lpp,lpp kya hai,lpp meaning,labour payment proposal,lpp full form',
     'What is LPP?',
     '<b>LPP</b> stands for <b>Labour Payment Proposal</b>. It contains the proposed wages and payment details for security personnel based on their monthly attendance. SDHOD generates the LPP, and Finance reviews and approves it.',10],

    // ─── ADMIN ──────────────────────────────────────────────────
    ['Admin','add user,create user,new user,register user,user banana,naya user',
     'How do I add a new user?',
     'Go to <b>Add Users</b> in the sidebar. Fill in the Employee ID, name, email, role, and password. Click <b>Add User</b> to create the account. The user will set up 2FA on first login.',10],

    ['Admin','add employee,import employee,new employee,employee import,bulk import,employee add,karmchari jodna',
     'How do I add or import employees?',
     'Go to <b>Add Employee</b> in the sidebar. You can add employees individually or <b>bulk import</b> from an Excel file (.xlsx). Download the sample template first to ensure the correct format.',10],

    ['Admin','unlock attendance,locked attendance,unlock,attendance unlock kaise kare',
     'How do I unlock attendance?',
     'Go to <b>Unlock Attendance</b> in the sidebar. Select the site, year, and month, then click <b>Unlock</b> to allow re-editing of previously locked attendance records.',10],

    ['Admin','attendance request,edit request,approve request,request approve kare',
     'How do I handle attendance edit requests?',
     'Go to <b>Attendance Request</b> in the sidebar. You will see pending edit requests from users. Review each request and click <b>Approve</b> or <b>Reject</b>.',8],

    ['Admin','basic pay,update pay,salary update,pay update,vetan badhao',
     'How do I update basic pay?',
     'Go to <b>Basic Pay Update</b> in the sidebar. Select employees and update their basic pay amounts. Changes will reflect in future wage and billing calculations.',8],

    ['Admin','extra manpower,add manpower,additional staff,extra log',
     'How do I add extra manpower?',
     'Go to <b>Add Extra Manpower</b> in the sidebar. Enter the details for temporary/additional security staff for a specific site and period.',8],

    ['Admin','download attendance,export attendance,attendance download kaise kare',
     'How do I download attendance data?',
     'Go to <b>Download Attendance</b> in the sidebar. Select the site, year, and month, then click <b>Download</b> to export as an Excel file.',8],

    ['Admin','wage report,salary report,wage calculation,vetan report',
     'How do I view the wage report?',
     'Go to <b>Wage Report</b> in the sidebar. Select the period and site to view calculated wages based on attendance data. You can also export it.',8],

    // ─── USER ───────────────────────────────────────────────────
    ['user','my attendance,view attendance,check attendance,meri attendance,attendance dekhna,attendance dikhao',
     'How do I view my attendance?',
     'Your attendance records are displayed on the <b>Dashboard</b>. Use the filters to select a specific date or status. You can see Present, Absent, Leave, and Overtime counts.',10],

    ['user','upload attendance,submit attendance,enter attendance,attendance upload kaise kare',
     'How do I upload attendance?',
     'Go to <b>Upload Attendance</b> in the sidebar. Select the site, year, and month, then upload the attendance Excel file. Ensure it follows the correct format (download the sample template).',10],

    ['user','update attendance,edit attendance,change attendance,correction,attendance badalna',
     'How do I update or edit attendance?',
     'Go to <b>Update Attendance</b> in the sidebar. Select the record you want to edit. Note: only unlocked records can be edited, and changes may require Admin approval.',10],

    // ─── ASO ────────────────────────────────────────────────────
    ['ASO','daily attendance,today attendance,check daily,aso dashboard,aaj ki attendance,daily report',
     'How do I check daily attendance?',
     'Your <b>ASO Dashboard</b> shows today\'s attendance summary including Present, Absent, Leave, and Overtime counts. Use filters to check specific dates or sites.',10],

    ['ASO','monthly attendance,monthly report,submit monthly,aso monthly,monthly submit kaise kare',
     'How do I manage monthly attendance?',
     'Go to <b>Monthly Attendance</b> from the sidebar. Review the monthly data for your area and <b>submit</b> it for APM approval.',10],

    // ─── APM ────────────────────────────────────────────────────
    ['APM','approve attendance,apm approve,monthly approval,attendance approve kaise kare',
     'How do I approve monthly attendance?',
     'Go to <b>Monthly Attendance</b> from the sidebar. Review reports submitted by ASOs and click <b>Approve</b> to forward to GM.',10],

    ['APM','reject,send back,return for correction,wapas bhejo',
     'Can I reject or send back a report?',
     'Yes, if you find discrepancies, you can <b>reject</b> the monthly report and it will be sent back to the ASO for corrections.',8],

    // ─── GM ─────────────────────────────────────────────────────
    ['GM','gm approve,approve monthly,gm approval,report approve kaise kare',
     'How do I approve monthly reports?',
     'Go to <b>Monthly Attendance</b> from the sidebar. Review reports approved by APM and click <b>Approve</b> to forward to HQSO.',10],

    // ─── HQSO ───────────────────────────────────────────────────
    ['HQSO','hqso approve,approve monthly,hqso approval',
     'How do I approve monthly attendance?',
     'Go to <b>Monthly Attendance</b> from the sidebar. Review reports approved by GM and click <b>Approve</b> to forward to SDHOD.',10],

    // ─── SDHOD ──────────────────────────────────────────────────
    ['SDHOD','generate lpc,create lpc,lpc generation,lpc banana,lpc nikalo,lpc kaise banaye',
     'How do I generate an LPC?',
     'Go to <b>Monthly LPP</b> from the sidebar, select the approved report, and click <b>Generate LPC</b>. The system creates the Labour Payment Certificate based on attendance and wage data.',10],

    ['SDHOD','monthly lpp,view lpp,lpp report,lpp dekhna',
     'How do I view monthly LPP?',
     'Go to <b>Monthly LPP</b> in the sidebar to view all Labour Payment Proposals with status, amounts, and breakdowns.',10],

    ['SDHOD','vv statement,verification,vv report,vv statement kaise banaye',
     'How do I export the VV Statement?',
     'Go to <b>VV Statement</b> in the sidebar. Select the period and click <b>Export</b> to download the Verification & Validation statement.',8],

    ['SDHOD','forward lpc,send to finance,lpc forward,finance ko bhejo',
     'How do I forward LPC to Finance?',
     'After generating the LPC, click <b>Forward to Finance</b>. The LPC will be sent for final approval and payment processing.',8],

    // ─── FINANCE ────────────────────────────────────────────────
    ['Finance','approve lpc,lpc approval,finance approve,lpc approve kaise kare',
     'How do I approve an LPC?',
     'Go to <b>Monthly LPP</b> in the sidebar. Review the LPC forwarded by SDHOD and click <b>Approve</b> to authorize payment.',10],

    ['Finance','finance lpp,view lpp,billing,payment,payment kaise hota',
     'How do I view monthly LPP/billing?',
     'Go to <b>Monthly LPP</b> in the sidebar to view Labour Payment Proposals with amounts, approval status, and payment details.',10],

    ['Finance','billing workflow,payment process,finance role,finance ka kaam',
     'What is the billing workflow?',
     'After SDHOD generates and forwards the LPC: <b>Finance</b> reviews → verifies amounts → approves for payment → processes billing. You are the final step in the approval chain.',8],
];

try {
    // Clear existing FAQs
    $pdo->exec("DELETE FROM chatbot_faqs");

    $stmt = $pdo->prepare("
        INSERT INTO chatbot_faqs (role, keywords, question, answer, priority)
        VALUES (?, ?, ?, ?, ?)
    ");

    $count = 0;
    foreach ($faqs as $faq) {
        $stmt->execute($faq);
        $count++;
    }

    echo "✅  Seeded <b>{$count}</b> FAQ entries into chatbot_faqs (with Hinglish support).<br>";
    echo "<br><strong>Knowledge base ready!</strong> The chatbot is now configured with English + Hinglish support.";

} catch (PDOException $e) {
    echo "❌  Seeding failed: " . htmlspecialchars($e->getMessage());
}
